### ISSUE TITLE
Post href has an issue.

### ISSUE THREAD

**Issue by redrails** [Rigter/Vapor#2]
On the main page when viewing all posts I've noticed that the URL Href is wrong, or at least for my blog it was wrong. It may not be a big issue but instead of directing posts to `/blog/posts/post/` it directs to `/blog/blog/posts/post` which obviously results in a 404.

To fix this, I edited the `Vapor/posts.php` file and on lines 8 and 13, removed `full_url();` call. I believe that `article_url()` should be quite enough.

**Comment by Rigter** [comment]
Amazing! Thank you ;)
